name: lerobot_vla_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg                          # dataset video decoding
  - pytorch::pytorch>=2.2.1,<2.6.0
  - pytorch::torchvision>=0.17.0,<0.21.0
  - pytorch::pytorch-cuda=12.1
  - pip:
    - packaging>=24.2,<26.0
    - "lerobot[smolvla]"