name: smolvla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg                          # dataset video decoding
  - pytorch::pytorch>=2.2.1
  - pytorch::torchvision>=0.17.0
  - pytorch::cpuonly
  - pip:
    - packaging>=24.2,<26.0
    - "lerobot[smolvla]"